// web/src/components/PrivateRoute.tsx
import { ReactNode } from 'react';
import { Navigate } from 'react-router-dom';
import { useAuth } from '@/lib/auth-context';

interface PrivateRouteProps {
  children: ReactNode;
}

const PrivateRoute = ({ children }: PrivateRouteProps) => {
  const { currentUser, loading, isWhitelisted } = useAuth();
  
  if (loading) {
    return <div className="flex justify-center items-center h-screen">Loading...</div>;
  }
  
  if (!currentUser) {
    return <Navigate to="/login" replace />;
  }
  
  if (!isWhitelisted) {
    return <Navigate to="/request-whitelist" replace />;
  }
  
  return <>{children}</>;
};

export default PrivateRoute;

// solidjs/src/components/PrivateRoute.tsx
import { Component, JSX } from 'solid-js';
import { Navigate } from '@solidjs/router';
import { useAuth } from '@/lib/auth-context';

interface PrivateRouteProps {
  children: JSX.Element;
}

const PrivateRoute: Component<PrivateRouteProps> = (props) => {
  const { currentUser, loading, isWhitelisted } = useAuth();
  
  if (loading()) {
    return <div class="flex justify-center items-center h-screen">Loading...</div>;
  }
  
  if (!currentUser()) {
    return <Navigate href="/login" />;
  }
  
  if (!isWhitelisted()) {
    return <Navigate href="/request-whitelist" />;
  }
  
  return <>{props.children}</>;
};

export default PrivateRoute;
