// src/aichat/components/MarkdownRenderer.tsx
import { useMemo } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkBreaks from "remark-breaks";
import supersub from "remark-supersub";
import CustomPre from "./CustomPre";
import TableRenderer from "./TableRenderer";

interface MarkdownRendererProps {
  children: string;
  isStreaming: boolean;
}

const MarkdownRenderer: React.FC<MarkdownRendererProps> = (props) => {
  const segments = useMemo(() => {
    const content = props.children || "";
    
    // If no pipes, no tables possible
    if (!content.includes('|')) {
      return [{ type: 'text' as const, content }];
    }

    const lines = content.split('\n');
    const result: Array<{ type: 'text' | 'table'; content: string }> = [];
    let textLines: string[] = [];
    let tableLines: string[] = [];
    let inTable = false;

    for (const line of lines) {
      const trimmed = line.trim();
      const isTableRow = trimmed.startsWith('|') && trimmed.endsWith('|');

      if (isTableRow) {
        if (!inTable) {
          // Save accumulated text before starting table
          if (textLines.length > 0) {
            result.push({ type: 'text', content: textLines.join('\n') });
            textLines = [];
          }
          inTable = true;
        }
        tableLines.push(line);
      } else {
        if (inTable) {
          // Save completed table
          if (tableLines.length > 0) {
            result.push({ type: 'table', content: tableLines.join('\n') });
            tableLines = [];
          }
          inTable = false;
        }
        textLines.push(line);
      }
    }

    // Flush remaining content
    if (tableLines.length > 0) {
      result.push({ type: 'table', content: tableLines.join('\n') });
    }
    if (textLines.length > 0) {
      result.push({ type: 'text', content: textLines.join('\n') });
    }

    return result.length > 0 ? result : [{ type: 'text' as const, content }];
  }, [props.children]);

  return (
    <div className="markdown-renderer">
      {segments.map((segment, idx) =>
        segment.type === 'table' ? (
          <TableRenderer
            key={idx}
            content={segment.content}
            isStreaming={props.isStreaming}
          />
        ) : (
          <ReactMarkdown
            key={idx}
            components={{
              pre: CustomPre as any,
              table: () => null,
              thead: () => null,
              tbody: () => null,
              tr: () => null,
              th: () => null,
              td: () => null
            }}
            remarkPlugins={[remarkGfm, remarkBreaks, supersub]}
            rehypePlugins={[]}
          >
            {segment.content}
          </ReactMarkdown>
        )
      )}
    </div>
  );
};

export default MarkdownRenderer;

// solidjs/src/aichat/components/MarkdownRenderer.tsx
import { Component, Show, createMemo } from "solid-js";
import { SolidMarkdown } from "solid-markdown";
import remarkGfm from "remark-gfm";
import remarkBreaks from "remark-breaks";
import supersub from "remark-supersub";
import CustomPre from "./CustomPre";
import TableRenderer from "./TableRenderer";

interface MarkdownRendererProps {
  children: string;
  isStreaming: boolean;
}

const MarkdownRenderer: Component<MarkdownRendererProps> = (props) => {
  const content = createMemo(() => props.children || "");

  // Check if content contains table markdown
  const hasTable = createMemo(() => {
    const text = content();
    return text.includes('|') && /\n\|[\s\-\w\|:]+\|\n/.test(text);
  });

  // Extract table content if present
  const tableContent = createMemo(() => {
    if (!hasTable()) return null;

    const text = content();
    const lines = text.split('\n');

    // Find table boundaries
    let tableStart = -1;
    let tableEnd = -1;

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();
      if (line.startsWith('|') && line.endsWith('|')) {
        if (tableStart === -1) {
          tableStart = i;
        }
        tableEnd = i;
      } else if (tableStart !== -1 && line !== '') {
        // Found end of table (non-empty line after table)
        break;
      }
    }

    if (tableStart !== -1 && tableEnd !== -1) {
      const tableLines = lines.slice(tableStart, tableEnd + 1);
      return tableLines.join('\n');
    }

    return null;
  });

  // Get non-table content
  const nonTableContent = createMemo(() => {
    if (!hasTable()) return content();

    const text = content();
    const tableMatch = tableContent();

    if (tableMatch) {
      return text.replace(tableMatch, '').trim();
    }

    return text;
  });

  return (
    <div class="markdown-renderer">
      <Show when={hasTable() && tableContent()}>
        <TableRenderer
          content={tableContent()!}
          isStreaming={props.isStreaming}
        />
      </Show>

      <Show when={nonTableContent()}>
        <SolidMarkdown
          components={{
            pre: CustomPre,
            table: () => null, // Disable table rendering in SolidMarkdown
            thead: () => null,
            tbody: () => null,
            tr: () => null,
            th: () => null,
            td: () => null
          }}
          children={nonTableContent()!}
          remarkPlugins={[remarkGfm, remarkBreaks, supersub]}
          rehypePlugins={[]}
        />
      </Show>
    </div>
  );
};

export default MarkdownRenderer;
